name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Format check
        run: pnpm format --check
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
      - name: Run E2E tests
        if: success()
        run: pnpm e2e
